"""Public API for exact-algorithm CAT-Surface GPU acceleration."""

# SPDX-License-Identifier: GPL-3.0-or-later

from .dartel_grid import (
    DeviceUnavailable,
    GridSpec,
    composition,
    composition_jacobian,
    dartel_step,
    expdef,
    fmg2_membrane,
    from_c_layout,
    initialise_objfun,
    jacobian_of_displacement,
    jac_div_smalldef,
    make_identity_map,
    apply_membrane_system,
    relax_membrane,
    regularization_operator,
    resolve_device,
    resize_field,
    sample_field,
    smalldef_jac,
    squaring_update,
    to_c_layout,
)
from .surface_stencil import SurfaceStencil, SurfaceStencilDevice
from .surface_rotation import (
    RotationCostInputs,
    RotationGridIndex,
    RotationGridIndexDevice,
    RotationSearchResult,
    official_seed_grid_angles,
)
from .rotation_pipeline import (
    RotationPipeline,
    read_rotation_points,
    read_rotation_values,
    run_rotation_pipeline,
    run_rotation_pipeline_from_files,
)
from .surface_warp import (
    DartelSolveResult,
    apply_flow_to_sphere,
    apply_flow_to_stenciled_sphere,
    clear_dartel_cuda_graph_cache,
    default_dartel_parameters,
    prepare_dartel_cuda_graph,
    solve_dartel_from_surfaces,
    solve_dartel_maps,
)
from .gpu_pipeline import (
    CatSurfaceGpuResult,
    GiftiMesh,
    read_gifti_mesh,
    run_cat_surface_gpu_pipeline,
    write_gifti_mesh,
)
from .surf2sphere import (
    CatSurf2SphereGpuResult,
    Surf2SphereTopology,
    convert_ellipsoid_to_sphere_with_surface_area,
    run_areal_smoothing_cuda,
    run_cat_surf2sphere_gpu,
    run_surf2sphere_preprocess_cuda,
    surface_area,
)
from .resources import bundled_binary, bundled_binary_names

__all__ = [
    "DeviceUnavailable",
    "GridSpec",
    "composition",
    "composition_jacobian",
    "dartel_step",
    "expdef",
    "fmg2_membrane",
    "from_c_layout",
    "initialise_objfun",
    "jacobian_of_displacement",
    "jac_div_smalldef",
    "make_identity_map",
    "apply_membrane_system",
    "relax_membrane",
    "regularization_operator",
    "resolve_device",
    "resize_field",
    "sample_field",
    "smalldef_jac",
    "squaring_update",
    "to_c_layout",
    "SurfaceStencil",
    "SurfaceStencilDevice",
    "RotationCostInputs",
    "RotationGridIndex",
    "RotationGridIndexDevice",
    "RotationSearchResult",
    "official_seed_grid_angles",
    "RotationPipeline",
    "read_rotation_points",
    "read_rotation_values",
    "run_rotation_pipeline",
    "run_rotation_pipeline_from_files",
    "DartelSolveResult",
    "apply_flow_to_sphere",
    "apply_flow_to_stenciled_sphere",
    "clear_dartel_cuda_graph_cache",
    "default_dartel_parameters",
    "prepare_dartel_cuda_graph",
    "solve_dartel_from_surfaces",
    "solve_dartel_maps",
    "CatSurfaceGpuResult",
    "GiftiMesh",
    "read_gifti_mesh",
    "run_cat_surface_gpu_pipeline",
    "write_gifti_mesh",
    "CatSurf2SphereGpuResult",
    "Surf2SphereTopology",
    "convert_ellipsoid_to_sphere_with_surface_area",
    "run_areal_smoothing_cuda",
    "run_cat_surf2sphere_gpu",
    "run_surf2sphere_preprocess_cuda",
    "surface_area",
    "bundled_binary",
    "bundled_binary_names",
]
